max_iterations: 100
checkpoint_interval: 10
log_level: "INFO"


llm:
  api_base: "https://llm.scads.ai/v1"
  #primary_model: "zai-org/GLM-5.2-FP8"
  primary_model: "Qwen/Qwen3-Coder-30B-A3B-Instruct"
  primary_model_weight: 1.0
  secondary_model: "openai/gpt-oss-120b"
  secondary_model_weight: 0.0
  temperature: 0.55
  top_p: 0.95
  max_tokens: 8192
  timeout: 180

prompt:
  system_message: |
    TODO


  num_top_programs: 2
  use_template_stochasticity: true

# Database configuration
database:
  population_size: 35  #changed: (70->35) Larger population for more diversity
  archive_size: 15  #changed: (30->15)
  num_islands: 5
  elite_selection_ratio: 0.3
  exploitation_ratio: 0.6  # Slightly lower to encourage exploration

# Evaluator configuration
evaluator:
  timeout: 180  # Extended timeout to allow for more complex optimization
  cascade_evaluation: false #changed: true -> false; a runtime warning suggested the change
  cascade_thresholds: [0.5, 0.8]
  parallel_evaluations: 2 #changed: 4->2 because of API backend rate limiting
  use_llm_feedback: true

# Evolution settings
diff_based_evolution: false
allow_full_rewrites: true
max_code_length: 2000